name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: gcc main.c
    - name: test run
      run: ./a.out
    - name: mkdir
      run: mkdir dist
    - name: mv
      run: mv a.out dist/a.out
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: a.out
        path: dist